insert into venue (name) values ('ODEON');
insert into venue (name) values ('VUE');
insert into venue (name) values ('SHOWCASE');
insert into venue (name) values ('CINEWORLD');
insert into venue (name) values ('EVERYMAN');

insert into movie (title, time_length, rating, genre, price, venue_id) values ('That Championship Season', '9:50 PM', 1, 'Drama', 15, 5);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Someone Like Him (Einer wie Bruno)', '7:06 AM', 1, 'Comedy|Drama', 14, 1);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Rage of Angels', '10:01 PM', 4, 'Action|Adventure|Drama|Romance', 17, 4);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Maniac', '10:19 PM', 5, 'Crime|Horror|Mystery|Romance|Thriller', 15, 2);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Pope''s Toilet, The (El bano del Papa)', '4:13 PM', 2, 'Drama', 12, 4);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('OSS 117: Cairo, Nest of Spies (OSS 117: Le Caire nid d''espions)', '4:26 PM', 4, 'Adventure|Comedy|Crime', 12, 4);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Changing Times (Les temps qui changent)', '12:01 PM', 3, 'Drama|Romance', 12, 1);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Mark of the Cop', '5:50 AM', 3, 'Crime|Drama|Romance', 15, 5);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Walking Tall', '6:59 AM', 3, 'Action', 11, 4);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Ricky Gervais Live 3: Fame', '6:39 AM', 4, 'Comedy', 16, 4);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Colorado Territory', '8:48 PM', 5, 'Western', 11, 2);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Dead Man''s Letters (Pisma myortvogo cheloveka)', '9:22 PM', 5, 'Drama|Film-Noir', 11, 5);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Hound of the Baskervilles, The', '8:10 AM', 1, 'Comedy|Crime|Mystery', 15, 5);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Aankhen', '7:47 PM', 2, 'Comedy|Crime|Thriller', 11, 5);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Majority of One, A', '8:09 PM', 4, 'Comedy|Drama|Romance', 12, 2);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Robin Williams: Weapons of Self Destruction', '11:17 PM', 5, 'Comedy', 11, 4);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Room 666 (Chambre 666)', '12:23 PM', 5, 'Documentary', 18, 2);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Shock Treatment', '2:42 AM', 3, 'Comedy|Musical|Sci-Fi', 10, 1);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Feast of July', '12:50 PM', 4, 'Drama', 10, 4);
insert into movie (title, time_length, rating, genre, price, venue_id) values ('Question of Silence, A (De stilte rond Christine M.)', '3:49 PM', 5, 'Drama', 15, 4);


insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '10:15 AM', 3, 12);
insert into timetable (date, time, venue_id, movie_id) values ('Friday', '2:37 AM', 1, 3);
insert into timetable (date, time, venue_id, movie_id) values ('Friday', '8:52 AM', 1, 13);
insert into timetable (date, time, venue_id, movie_id) values ('Tuesday', '3:18 AM', 4, 13);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '4:57 AM', 4, 11);
insert into timetable (date, time, venue_id, movie_id) values ('Monday', '2:22 AM', 5, 3);
insert into timetable (date, time, venue_id, movie_id) values ('Saturday', '11:50 PM', 4, 1);
insert into timetable (date, time, venue_id, movie_id) values ('Saturday', '5:34 AM', 1, 19);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '10:51 AM', 4, 9);
insert into timetable (date, time, venue_id, movie_id) values ('Tuesday', '12:04 AM', 2, 16);
insert into timetable (date, time, venue_id, movie_id) values ('Saturday', '11:22 PM', 3, 19);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '5:07 AM', 3, 14);
insert into timetable (date, time, venue_id, movie_id) values ('Tuesday', '12:11 PM', 3, 13);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '11:53 PM', 1, 7);
insert into timetable (date, time, venue_id, movie_id) values ('Saturday', '3:18 AM', 4, 17);
insert into timetable (date, time, venue_id, movie_id) values ('Saturday', '9:09 PM', 5, 15);
insert into timetable (date, time, venue_id, movie_id) values ('Monday', '1:15 PM', 2, 19);
insert into timetable (date, time, venue_id, movie_id) values ('Monday', '3:43 AM', 4, 4);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '6:13 AM', 4, 5);
insert into timetable (date, time, venue_id, movie_id) values ('Tuesday', '9:46 AM', 1, 17);
insert into timetable (date, time, venue_id, movie_id) values ('Friday', '4:56 AM', 1, 9);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '12:24 AM', 2, 13);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '2:46 AM', 2, 20);
insert into timetable (date, time, venue_id, movie_id) values ('Saturday', '11:44 AM', 5, 15);
insert into timetable (date, time, venue_id, movie_id) values ('Monday', '10:49 AM', 1, 5);
insert into timetable (date, time, venue_id, movie_id) values ('Monday', '9:54 AM', 1, 9);
insert into timetable (date, time, venue_id, movie_id) values ('Tuesday', '2:38 AM', 1, 9);
insert into timetable (date, time, venue_id, movie_id) values ('Sunday', '12:33 PM', 4, 3);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '8:26 PM', 2, 14);
insert into timetable (date, time, venue_id, movie_id) values ('Sunday', '1:51 PM', 4, 20);
insert into timetable (date, time, venue_id, movie_id) values ('Monday', '3:12 AM', 4, 17);
insert into timetable (date, time, venue_id, movie_id) values ('Tuesday', '1:38 AM', 5, 14);
insert into timetable (date, time, venue_id, movie_id) values ('Monday', '2:16 PM', 4, 11);
insert into timetable (date, time, venue_id, movie_id) values ('Sunday', '12:04 PM', 5, 19);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '3:49 AM', 3, 18);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '9:31 AM', 3, 6);
insert into timetable (date, time, venue_id, movie_id) values ('Sunday', '2:16 AM', 1, 13);
insert into timetable (date, time, venue_id, movie_id) values ('Sunday', '6:05 AM', 1, 4);
insert into timetable (date, time, venue_id, movie_id) values ('Tuesday', '11:19 AM', 3, 14);
insert into timetable (date, time, venue_id, movie_id) values ('Tuesday', '1:51 PM', 5, 11);
insert into timetable (date, time, venue_id, movie_id) values ('Saturday', '4:03 PM', 4, 3);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '9:24 PM', 1, 7);
insert into timetable (date, time, venue_id, movie_id) values ('Saturday', '8:36 PM', 5, 11);
insert into timetable (date, time, venue_id, movie_id) values ('Friday', '10:18 PM', 3, 2);
insert into timetable (date, time, venue_id, movie_id) values ('Friday', '4:37 AM', 1, 19);
insert into timetable (date, time, venue_id, movie_id) values ('Sunday', '7:01 PM', 2, 8);
insert into timetable (date, time, venue_id, movie_id) values ('Friday', '1:58 AM', 5, 10);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '12:20 PM', 5, 7);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '4:26 PM', 5, 1);
insert into timetable (date, time, venue_id, movie_id) values ('Monday', '7:15 AM', 5, 1);
insert into timetable (date, time, venue_id, movie_id) values ('Saturday', '10:15 PM', 3, 14);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '9:42 PM', 3, 10);
insert into timetable (date, time, venue_id, movie_id) values ('Sunday', '12:02 AM', 4, 11);
insert into timetable (date, time, venue_id, movie_id) values ('Friday', '8:26 AM', 5, 16);
insert into timetable (date, time, venue_id, movie_id) values ('Saturday', '10:05 AM', 5, 11);
insert into timetable (date, time, venue_id, movie_id) values ('Tuesday', '9:32 AM', 5, 10);
insert into timetable (date, time, venue_id, movie_id) values ('Tuesday', '4:04 PM', 4, 9);
insert into timetable (date, time, venue_id, movie_id) values ('Friday', '10:53 AM', 2, 10);
insert into timetable (date, time, venue_id, movie_id) values ('Friday', '7:45 PM', 1, 5);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '9:56 AM', 1, 8);
insert into timetable (date, time, venue_id, movie_id) values ('Monday', '4:28 AM', 4, 15);
insert into timetable (date, time, venue_id, movie_id) values ('Sunday', '8:36 AM', 1, 16);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '11:19 AM', 1, 10);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '5:45 AM', 2, 17);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '9:02 PM', 2, 11);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '12:29 AM', 1, 19);
insert into timetable (date, time, venue_id, movie_id) values ('Sunday', '11:22 PM', 5, 5);
insert into timetable (date, time, venue_id, movie_id) values ('Tuesday', '8:42 AM', 4, 13);
insert into timetable (date, time, venue_id, movie_id) values ('Tuesday', '12:20 PM', 2, 9);
insert into timetable (date, time, venue_id, movie_id) values ('Saturday', '2:25 PM', 4, 19);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '1:43 AM', 5, 5);
insert into timetable (date, time, venue_id, movie_id) values ('Sunday', '9:34 AM', 5, 10);
insert into timetable (date, time, venue_id, movie_id) values ('Friday', '3:29 PM', 4, 4);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '1:55 AM', 3, 17);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '5:27 AM', 1, 10);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '11:23 AM', 1, 8);
insert into timetable (date, time, venue_id, movie_id) values ('Monday', '2:28 PM', 2, 16);
insert into timetable (date, time, venue_id, movie_id) values ('Friday', '1:28 PM', 5, 19);
insert into timetable (date, time, venue_id, movie_id) values ('Monday', '10:39 PM', 1, 1);
insert into timetable (date, time, venue_id, movie_id) values ('Sunday', '3:00 AM', 2, 7);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '8:03 PM', 4, 8);
insert into timetable (date, time, venue_id, movie_id) values ('Saturday', '7:46 PM', 5, 9);
insert into timetable (date, time, venue_id, movie_id) values ('Tuesday', '12:59 AM', 5, 12);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '6:32 AM', 3, 5);
insert into timetable (date, time, venue_id, movie_id) values ('Sunday', '10:27 PM', 3, 13);
insert into timetable (date, time, venue_id, movie_id) values ('Monday', '5:12 AM', 1, 18);
insert into timetable (date, time, venue_id, movie_id) values ('Saturday', '12:10 AM', 4, 8);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '9:15 PM', 5, 14);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '4:17 PM', 3, 16);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '11:53 PM', 3, 11);
insert into timetable (date, time, venue_id, movie_id) values ('Friday', '10:53 PM', 5, 10);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '2:22 AM', 4, 12);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '9:50 AM', 5, 18);
insert into timetable (date, time, venue_id, movie_id) values ('Thursday', '1:57 AM', 3, 10);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '10:04 PM', 1, 1);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '8:11 PM', 1, 9);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '2:03 PM', 4, 15);
insert into timetable (date, time, venue_id, movie_id) values ('Friday', '3:29 AM', 1, 10);
insert into timetable (date, time, venue_id, movie_id) values ('Wednesday', '11:09 AM', 5, 5);
insert into timetable (date, time, venue_id, movie_id) values ('Tuesday', '1:38 AM', 3, 3);


